# Solution {-}

In [1]:
from numpy import array, printoptions, random, zeros
from scipy.linalg import sqrtm, cholesky

# State vector
x = array([[-16.5],
           [-6.6],
           [2.9]])

# Covariance matrix
P = array([[ 3.2, -1.2,  0.2],
           [-1.2,  4.5,  0.02],
           [ 0.2,  0.02, 1.2]])

# Transistion 
phi = array([[1, 1, 0],
             [0, 1, 0],
             [0, 0, 0.98]])

# Process noise matrix
Q = array([[1/3, 1/2, 0],
           [1/2,   1, 0],
           [  0,   0, 0.01]])


# Time update
xp = phi@x
Pp = phi@P@phi.T + Q

with printoptions(precision=3, suppress=True):
    print(xp)
    print(Pp)

[[-23.1  ]
 [ -6.6  ]
 [  2.842]]
[[5.633 3.8   0.216]
 [3.8   5.5   0.02 ]
 [0.216 0.02  1.162]]


## Monte Carlo Simulation



In [2]:
n = 10000
sum = zeros([3, 1])
sumsq = zeros([3, 3])

# Matrix square root
Psqrt = sqrtm(P)
Qsqrt = sqrtm(Q)

# Cholesky
#Psqrt = cholesky(P)
#Qsqrt = cholesky(Q)

for i in range(0, n):
    xs = x + Psqrt@random.normal(0, 1, [3, 1])
    ws = Qsqrt@random.normal(0, 1, [3, 1])
    xp = phi@xs + ws
    
    sum = sum + xp
    sumsq = sumsq + xp@xp.T
    
xpm = sum/n
Ppm = sumsq/n - xpm@xpm.T

with printoptions(precision=5, suppress=True):
    print(xpm)
    print(Ppm)

[[-23.04095]
 [ -6.61459]
 [  2.83809]]
[[5.53555 3.75283 0.24149]
 [3.75283 5.56028 0.01002]
 [0.24149 0.01002 1.16048]]
