# Solution {-}

PVA model

In [1]:
from sympy import Matrix, symbols, sqrt, eye, integrate
from lib.vanloan import numeval

q, dt = symbols('q dt')

F = Matrix([[0, 1, 0],
            [0, 0, 1],
            [0, 0, 0]])

G = Matrix([[0],
            [0],
            [sqrt(q)]])

phi = eye(3) + F*dt + (F*dt)**2/2
phi

Matrix([
[1, dt, dt**2/2],
[0,  1,      dt],
[0,  0,       1]])

In [2]:
# Process noise
Q = integrate(phi@G@G.T@phi.T, dt)
Q

Matrix([
[dt**5*q/20, dt**4*q/8, dt**3*q/6],
[ dt**4*q/8, dt**3*q/3, dt**2*q/2],
[ dt**3*q/6, dt**2*q/2,      dt*q]])

Numerical example

In [3]:
from numpy import array, zeros, arange
import matplotlib.pyplot as plt

# System parameters
dt = 0.1
q = 1

F = array([[0, 1, 0],
           [0, 0, 1],
           [0, 0, 0]])

G = array([[0],
           [0],
           [sqrt(q)]])

# Numerical evaluation
[phi, Q_true] = numeval(F, G, dt)

# Process noise approximation
Q_approx = array([[0, 0, 0],
                  [0, 0, 0],
                  [0, 0, q*dt]])

# Plot vectors
var_true = []
var_approx = []

# Initial covariance
P = zeros([3, 3])
for i in range(0, 200):
    P = phi@P@phi.T + Q_true
    var_true.append(P)

# Initial covariance
P = zeros([3, 3])
for i in range(0, 200):
    P = phi@P@phi.T + Q_approx
    var_approx.append(P)

# Difference at step 200
print(var_true[199] - var_approx[199])

[[1.99333335e+03 1.99500000e+02 9.98333333e+00]
 [1.99500000e+02 1.99666667e+01 1.00000000e+00]
 [9.98333333e+00 1.00000000e+00 0.00000000e+00]]
