# Solution {-}

PVA Markov model

In [1]:
from sympy import Matrix, symbols, sqrt, eye, integrate, inverse_laplace_transform

s, dt, beta, q = symbols('s dt beta q', positive=True)

F = Matrix([[0, 1, 0],
            [0, 0, 1],
            [0, 0, -beta]])

G = Matrix([[0],
            [0],
            [sqrt(q)]])

phi = inverse_laplace_transform((s*eye(3) - F).inv(), s, dt)
phi

Matrix([
[1, dt, dt/beta - 1/beta**2 + exp(-beta*dt)/beta**2],
[0,  1,                 1/beta - exp(-beta*dt)/beta],
[0,  0,                               exp(-beta*dt)]])

In [2]:
# Process noise
Q = integrate(phi@G@G.T@phi.T, dt)
Q

Matrix([
[dt**3*q/(3*beta**2) - dt**2*q/beta**3 + dt*q/beta**4 + (-4*beta**5*dt*q*exp(-beta*dt) - beta**4*q*exp(-2*beta*dt))/(2*beta**9), dt**2*q/(2*beta**2) - dt*q/beta**3 + (beta**4*q*exp(-2*beta*dt) + (2*beta**5*dt*q - 2*beta**4*q)*exp(-beta*dt))/(2*beta**8), (-2*beta**3*dt*q*exp(-beta*dt) - beta**2*q*exp(-2*beta*dt))/(2*beta**5)],
[   dt**2*q/(2*beta**2) - dt*q/beta**3 + (beta**4*q*exp(-2*beta*dt) + (2*beta**5*dt*q - 2*beta**4*q)*exp(-beta*dt))/(2*beta**8),                                          dt*q/beta**2 + (4*beta**3*q*exp(-beta*dt) - beta**3*q*exp(-2*beta*dt))/(2*beta**6),    (-2*beta**2*q*exp(-beta*dt) + beta**2*q*exp(-2*beta*dt))/(2*beta**4)],
[                                                       (-2*beta**3*dt*q*exp(-beta*dt) - beta**2*q*exp(-2*beta*dt))/(2*beta**5),                                                        (-2*beta**2*q*exp(-beta*dt) + beta**2*q*exp(-2*beta*dt))/(2*beta**4),                                             -q*exp(-2*beta*dt)/(2*beta)]])

In [3]:
from numpy import array, sqrt
from lib.vanloan import numeval

# System conditions
dt = 0.1
beta = 0.2
q = 10

F = array([[0, 1, 0],
           [0, 0, 1],
           [0, 0, -beta]])

G = array([[0],
           [0],
           [sqrt(q)]])

# Numerical evaulation
[phi, Q] = numeval(F, G, dt)

# Transition matrix
print(phi)

# Process noise covariance matrix
print(Q)

[[1.         0.1        0.00496683]
 [0.         1.         0.09900663]
 [0.         0.         0.98019867]]
[[4.94483906e-06 1.23347134e-04 1.63369713e-03]
 [1.23347134e-04 3.28379669e-03 4.90115674e-02]
 [1.63369713e-03 4.90115674e-02 9.80264021e-01]]
